# @no-cookie-jar

POST {{baseUrl}}/auth/register
Accept: application/json

{
    "username": "newuser",
    "password": "123456",
    "email": "2@qq.com",
    "first_name":"111",
    "last_name":"111"
}